server:
  port: 80
  
master:
 user:
  name: NIT-RAGHU
  email: kavi20900@gmail.com
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: kavi20900
    password: Rechargemaar
    properties:
     mail:
     smtp:
      starttls:
      enable: true
               